# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [staging] api-service'

env:
  AZURE_WEBAPP_NAME: 'IBF-staging'
  AZURE_WEBAPP_PACKAGE_PATH: services/api-service

defaults:
  run:
    working-directory: services/api-service

permissions:
  actions: read
  deployments: write

on:
  workflow_call:
    inputs:
      gitRef:
        description: 'Version-tag or branch-name'
        type: string
        required: true
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Version-tag or branch-name'
        type: string
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment: 'staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Service
        id: build
        uses: ./.github/actions/build-service
        with:
          servicePath: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure App Service
        # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
        # Also, see: https://github.com/Azure/actions-workflow-samples
        id: deploy_to_aas
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/artifact.zip'
          type: zip
          clean: true

      - name: Finish
        run: |
          echo "Build version: ${{ steps.build.outputs.build_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aas.outputs.webapp-url }}>" >> $GITHUB_STEP_SUMMARY
